# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages


# Course-site specific configuration:
course:
  # Enter a base path if needed; not necessary for testing at localhost:4000/
  # or if your site is hosted at a simple URL like http://example.com/
  # But, if something comes after the .com/, you should enter it here.
  # E.g., for http://example.com/530/ you'd enter 530/ for base_path:
  base_path: cdm2025spring/
  # base_path: /
  # E.g., ENGL 536
  number: ENGCMP 610
  name: Composing Digital Media
  university: University of Pittsburgh
  # Keep the description brief, about 140 chars
  description: Making the most of multiple modes
  # E.g., Spring 2013:
  term: Spring 2025
  slugterm: 2025spring
  time: MW 1:00-2:15pm
  room: CL 435 or by Zoom in case of emergency
  dml_hours: tbd
      # been announced as Mondays from 2:30 - 4:30 PM; Tuesdays from 3:00 - 6:00 PM; and Wednesdays from 3:00 - 4:00 PM
  featured_image: assets/img/course-title.gif
  featured_alt: animating media through replication, revision, responsiveness, rearrangement, remix, and more.
  instructor:
    name: Benjamin Miller
    office: CL 617-N and Zoom
    office_hours: MW 11:30am–12:50pm and 2:30-3:15pm (i.e. an hour before or after class, minus some transit time)
    email: millerb@pitt.edu
    # No @ before your username; e.g., twitter, not @twitter
    twitter: benmiller314
# github: [metadata]
github_url: https://benmiller314.github.io/cdm2025spring
repo_url: https://github.com/benmiller314/cdm2025spring
canvas_url: https://canvas.pitt.edu/courses/
theme: jekyll-theme-time-machine
